const Neighborhood = [
	{name: 'LIBERDADE', id:1},
	{name: 'MALHAMPSENE', id:2},
	{name: 'MACHAVA', id:3},
	{name: 'MATOLA_GARE', id:4},
	{name: 'MATOLA_SANTOS', id:5},
	{name: 'CIDADE_MATOLA', id:6},
	{name: 'CINEMA_700', id:7},
	{name: 'FOMENTO', id:8},
	{name: 'SIAL', id:9},
	{name: 'ZUIDE', id:10},
	{name: 'MACHAVA_TREVO', id:11},
	{name: 'T3', id:12},
	{name: 'ZIMPETO', id:13},
	{name: 'MAGOANINE', id:14},
	{name: 'GWAVA', id:15},
	{name: 'MATEQUE', id:16},
	{name: 'MICHAFUTENE', id:17},
	{name: 'MAGAWANINE', id:18},
	{name: 'NOVO_CEMITERIO', id:19},
	{name: 'XIPAMANINE', id:20},
	{name: 'BOQUISSO', id:21},
	{name: 'BOBOLE', id:22},
	{name: 'SANTA_ISABELA', id:23},
	{name: 'TCHUMENE', id:24},
	{name: 'INFULENE', id:25},
	{name: 'MATLEMELE', id:26},
	{name: 'INTAKA', id:27},
	{name: 'MAHOTAS', id:28},
	{name: 'XIQUELENE', id:29},
	{name: 'COMPONE', id:30},
	{name: 'MAFALALA', id:31},
	{name: 'ALBAZINE', id:32},
	{name: 'MALHAZINE', id:33},
	{name: 'FERROVIARIO', id:34},
	{name: 'CHOUPAL', id:35},
	{name: 'INHAGOIA', id:36},
	{name: 'MAXAQUENE', id:37},
	{name: 'COSTA_DO_SOL_TRIUNFO', id:38},
	{name: 'BAIRRO_CENTRAL', id:39},
	{name: 'MAVALANE', id:40},
	{name: 'NKOBE', id:41},
	{name: 'KHONGOLOTE', id:42},
	{name: 'BENFICA', id:43},
	{name: 'ZONA_VERDE', id:44},
	{name: 'MULOMBELA', id:45},
	{name: 'MATENDENE', id:46}

]


export default Neighborhood;